Repository woowa-techcamp-2021/store-2, pull requests merged in 2021-08, with the labels that each got.

#10 Feature/#4 프론트엔드 세팅
  .gitignore
  client/.eslintrc.json
  client/.prettierrc
  client/config/webpack.common.js
  client/config/webpack.dev.js
  client/config/webpack.prod.js
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.tsx
  client/src/components/common/layout.tsx
  client/src/index.tsx
  client/src/pages/main-page.tsx
  client/src/styles/reset.css
  client/src/styles/variables.css
  client/tsconfig.json
  client/yarn.lock
Labels: front-end, setting, pair, 중요도-blocker

#12 Feature/#9 리덕스 예시 코드 작성
  client/.prettierrc
  client/src/App.tsx
  client/src/components/common/layout.tsx
  client/src/components/example/counter.tsx
  client/src/containers/counter-container.tsx
  client/src/index.tsx
  client/src/store/counter.ts
  client/src/store/index.ts
Labels: front-end, pair, 중요도-blocker

#13 Feature/#6 유틸함수 설정
  .github/PULL_REQUEST_TEMPLATE.md
  client/.eslintrc.json
  client/src/App.tsx
  client/src/hooks/use-inputs.ts
  client/src/utils/api/auth.ts
  client/src/utils/api/request.ts
  client/src/utils/api/types.ts
Labels: front-end, setting, pair, 중요도-blocker

#14 Feature/#5 라우터 컴포넌트 생성
  .github/PULL_REQUEST_TEMPLATE.md
  client/public/index.html
  client/src/App.tsx
  client/src/lib/router/components/browser-router.tsx
  client/src/lib/router/components/link.tsx
  client/src/lib/router/components/route.tsx
  client/src/lib/router/components/switch.tsx
  client/src/lib/router/context/route-context.ts
  client/src/lib/router/context/router-context.ts
  client/src/lib/router/hooks/use-history.ts
  client/src/lib/router/hooks/use-params.ts
  client/src/lib/router/index.ts
  client/src/lib/router/path-validation.ts
  client/src/pages/index.ts
  client/src/pages/not-found-page.tsx
  client/src/pages/user-page.tsx
Labels: front-end, pair, 중요도-blocker

#17 docs: README 업데이트
  README.md
Labels: documentation, 중요도-trival

#20 FEATURE/#16 자동 배포를 위한 github workflow 작성
  .github/workflows/deploy.yml
  .github/workflows/lint-check.yml
  appspec.yml
  scripts/after-deploy.sh
  server/package.json
Labels: back-end, setting, 중요도-major

#21 Refactor/#19 짝팀 리뷰 반영
  client/.eslintrc.json
  client/.prettierrc
  client/config/webpack.common.js
  client/config/webpack.dev.js
  client/config/webpack.prod.js
  client/package.json
  client/src/App.tsx
  client/src/containers/counter-container.tsx
  client/src/index.tsx
  client/src/lib/router/components/browser-router.tsx
  client/src/lib/router/components/route.tsx
  client/src/lib/router/components/switch.tsx
  client/src/lib/router/path-validation.ts
  client/src/pages/main-page.tsx
  client/src/styles/reset.css
  client/src/styles/styled.d.ts
  client/src/styles/theme.tsx
  client/src/styles/variables.css
  client/src/utils/api/auth.ts
  client/src/utils/api/request.ts
  client/yarn.lock
Labels: setting, 중요도-trival

#22 Feature/#15 프론트엔드 테스트 코드 작성 및 절대경로 수정
  .gitignore
  client/.eslintrc.json
  client/config/webpack.common.js
  client/jest.config.js
  client/package.json
  client/setup-tests.ts
  client/src/App.tsx
  client/src/components/saga-example/counter.tsx
  client/src/components/test-example/Counter.test.tsx
  client/src/components/test-example/Counter.tsx
  client/src/components/test-example/LoginForm.test.tsx
  client/src/components/test-example/LoginForm.tsx
  client/src/components/test-example/NotFound.test.tsx
  client/src/components/test-example/NotFound.tsx
  client/src/components/test-example/Profile.test.tsx
  client/src/components/test-example/Profile.tsx
  client/src/containers/counter-container.tsx
  client/src/pages/index.ts
  client/src/pages/main-page.tsx
  client/src/pages/saga-axios-page.tsx
  client/src/pages/saga-counter-page.tsx
  client/src/pages/test-page.tsx
  client/src/store/counter.ts
  client/src/store/index.ts
  client/src/store/test-example/api.ts
  client/src/store/test-example/ex.test.ts
  client/src/store/test-example/ex.ts
  client/src/store/test-example/ex2.test.ts
  client/src/store/test-example/ex2.ts
  client/src/store/test-example/ex3.test.ts
  client/src/store/test-example/ex3.ts
  client/src/test-example/easy.test.ts
  client/src/test-example/promise.test.ts
  client/tsconfig.json
  client/yarn.lock
Labels: bug, feature, front-end, setting, 중요도-major

#24 Feature/#15 테스트 코드 구조 수정
  .github/workflows/lint-check.yml
  .gitignore
  client/jest.config.js
  client/src/components/test-example/__test__/Counter.test.tsx
  client/src/components/test-example/__test__/LoginForm.test.tsx
  client/src/components/test-example/__test__/NotFound.test.tsx
  client/src/components/test-example/__test__/Profile.test.tsx
  client/src/pages/saga-axios-page.tsx
  client/src/store/test-example/api.ts
  client/src/test-example/easy.test.ts
  client/src/test-example/promise.test.ts
Labels: front-end, 중요도-trival

#31 Feature/#25 로그인 API
  server/.eslintrc.json
  server/.mock.env
  server/.prettierrc
  server/package.json
  server/src/config/constants.ts
  server/src/controllers/auth.ts
  server/src/controllers/test.ts
  server/src/loaders/express.ts
  server/src/models/address.ts
  server/src/models/category.ts
  server/src/models/index.ts
  server/src/models/item.ts
  server/src/models/order.ts
  server/src/models/review.ts
  server/src/models/user.ts
  server/src/repositories/auth.ts
  server/src/repositories/test.ts
  server/src/routes/auth/index.ts
  server/src/routes/index.ts
  server/src/routes/test/index.ts
  server/src/services/auth.ts
  server/src/services/test.ts
  server/src/utils/crypto.ts
  server/src/utils/env.ts
  server/src/utils/error/error-generator.ts
  server/src/utils/error/error-handler.ts
  server/src/utils/jwt.ts
  server/src/validation/auth.ts
  server/src/validation/test.ts
  server/yarn.lock
Labels: feature, back-end, 중요도-blocker

#36 Feature/#27 인증 및 토큰 재발행 API
  server/src/controllers/auth.ts
  server/src/controllers/user.ts
  server/src/middlewares/testMiddleware.ts
  server/src/middlewares/validateToken.ts
  server/src/routes/auth/index.ts
  server/src/services/auth.ts
  server/src/utils/jwt.ts
Labels: feature, back-end, 중요도-blocker

#38 Feature/#29 레이아웃 컴포넌트 생성
  client/.eslintrc.json
  client/config/webpack.common.js
  client/file-transformer.js
  client/jest.config.js
  client/public/favicon.ico
  client/public/favicon.png
  client/src/assets/icons/tent.png
  client/src/assets/images/brick.png
  client/src/assets/images/brick_mobile.png
  client/src/assets/images/logo.png
  client/src/assets/images/logo_tent.png
  client/src/assets/images/tent.png
  client/src/components/common/__test__/logo.test.tsx
  client/src/components/common/__test__/navbar.test.tsx
  client/src/components/common/layout.tsx
  client/src/components/common/logo.tsx
  client/src/components/common/navbar.tsx
  client/src/components/index.ts
  client/src/components/layout/__test__/footer.test.tsx
  client/src/components/layout/__test__/header.test.tsx
  client/src/components/layout/__test__/layout.test.tsx
  client/src/components/layout/footer.tsx
  client/src/components/layout/header.tsx
  client/src/components/layout/index.tsx
  client/src/hooks/use-window-size.ts
  client/src/lib/router/components/link.tsx
  client/src/pages/main-page.tsx
  client/src/pages/user-page.tsx
  client/src/styles/img.d.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.tsx
Labels: front-end, 중요도-blocker

#41 Feature/#33 로그인 기능 및 ui
  client/config/webpack.common.js
  client/src/App.tsx
  client/src/components/auth/login-button.tsx
  client/src/components/auth/login-form.tsx
  client/src/components/auth/login-input.tsx
  client/src/components/saga-example/axios.tsx
  client/src/containers/axios-container.tsx
  client/src/containers/login-container.tsx
  client/src/pages/index.ts
  client/src/pages/login-page.tsx
  client/src/pages/saga-axios-page.tsx
  client/src/store/auth.ts
  client/src/store/axios.ts
  client/src/store/index.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.tsx
  client/src/utils/api/auth.ts
  client/src/utils/api/client.ts
  client/src/utils/api/request.ts
  server/package.json
Labels: front-end, 중요도-blocker

#45 Feature/#39 정적 페이지 생성
  client/src/components/layout/footer.tsx
  client/src/components/layout/index.tsx
  client/src/pages/__test__/not-found-page.test.tsx
  client/src/pages/not-found-page.tsx
  client/src/styles/styled.d.ts
  client/src/styles/theme.tsx
Labels: front-end, 중요도-trival

#46 Feature/#40 카테고리 불러오기 API 구현
  server/src/config/constants.ts
  server/src/controllers/category.ts
  server/src/loaders/sequelize.ts
  server/src/models/category.ts
  server/src/repositories/category.ts
  server/src/routes/categories/index.ts
  server/src/routes/index.ts
  server/src/routes/users/index.ts
  server/src/services/category.ts
  server/src/utils/error/error-handler.ts
Labels: back-end, 중요도-major

#58 Feature/#57 썸네일 데이터 타입 변경
  server/src/models/item.ts
Labels: feature, back-end, refactor, 중요도-major

#56 Feature/#51 사가 커스텀 함수 만들기 + 로딩
  client/.eslintrc.json
  client/package.json
  client/src/containers/login-container.tsx
  client/src/containers/signup-container.tsx
  client/src/index.tsx
  client/src/store/auth.ts
  client/src/store/index.ts
  client/src/store/loading.ts
  client/src/utils/saga-utils/index.ts
  client/yarn.lock
Labels: front-end, refactor, 중요도-minor

#60 Feature/#42 CSS-in-JS 개발
  client/package.json
  client/public/index.html
  client/src/components/auth/form.tsx
  client/src/components/auth/logout-modal.tsx
  client/src/components/auth/success-modal.tsx
  client/src/components/common/footer.tsx
  client/src/components/common/header.tsx
  client/src/components/common/layout.tsx
  client/src/components/common/logo.tsx
  client/src/components/common/modal.tsx
  client/src/components/common/navbar.tsx
  client/src/components/form/button.tsx
  client/src/components/form/input.tsx
  client/src/components/smart-menu/index.tsx
  client/src/components/smart-menu/large-menu.tsx
  client/src/components/smart-menu/medium-menu.tsx
  client/src/components/smart-menu/small-menu.tsx
  client/src/lib/woowahan-components/components/create-global-style.tsx
  client/src/lib/woowahan-components/components/theme-provider.tsx
  client/src/lib/woowahan-components/components/woowahan-component.tsx
  client/src/lib/woowahan-components/configs/tag-names.ts
  client/src/lib/woowahan-components/hooks/use-theme.ts
  client/src/lib/woowahan-components/index.ts
  client/src/lib/woowahan-components/utils/generate-id.ts
  client/src/lib/woowahan-components/utils/parse-string.ts
  client/src/pages/not-found-page.tsx
  client/src/pages/signup-page.tsx
  client/src/styles/styled.d.ts
  client/src/styles/theme.tsx
  client/yarn.lock
Labels: feature, front-end, 중요도-minor

#63 Feature/#59 oauth 로그인 구현 + 서버 코드 일부 수정
  client/src/App.tsx
  client/src/components/auth/form.tsx
  client/src/components/item/item-list.tsx
  client/src/containers/login-container.tsx
  client/src/containers/signup-container.tsx
  client/src/index.tsx
  client/src/pages/auth-page.tsx
  client/src/pages/index.ts
  client/src/store/auth.ts
  client/src/types/auth.ts
  client/src/utils/api/auth.ts
  server/src/config/constants.ts
  server/src/config/db.ts
  server/src/controllers/auth.ts
Labels: front-end, back-end, refactor, 중요도-blocker

#67 Feature/#66 검색어 자동완성 API
  server/package.json
  server/src/controllers/search.ts
  server/src/models/item.ts
  server/src/repositories/search.ts
  server/src/routes/index.ts
  server/src/routes/search/index.ts
  server/src/services/search.ts
  server/yarn.lock
Labels: feature, back-end, 중요도-major

#68 Feature/#65 아이템리스트 백엔드 완성
  server/src/config/constants.ts
  server/src/controllers/items.ts
  server/src/loaders/sequelize.ts
  server/src/models/item.ts
  server/src/repositories/items.ts
  server/src/routes/index.ts
  server/src/routes/items/index.ts
  server/src/services/items.ts
  server/src/utils/error/error-handler.ts
Labels: front-end, 중요도-blocker

#71 Feature/#53 검색창 컴포넌트
  client/src/assets/icons/x.png
  client/src/components/common/layout.tsx
  client/src/components/search-bar/__test__/search-bar.test.tsx
  client/src/components/search-bar/index.tsx
  client/src/components/search-bar/recent-keyword-box.tsx
  client/src/containers/search-container.tsx
  client/src/hooks/use-out-side-click.ts
  client/src/pages/main-page.tsx
  client/src/store/index.ts
  client/src/store/item.ts
  client/src/styles/theme.tsx
  client/src/utils/api/item.ts
  server/src/repositories/search.ts
Labels: feature, front-end, 중요도-blocker

#77 Feature/#74 woowahan-components 이름 변경
  client/src/components/auth/form.tsx
  client/src/components/auth/logout-modal.tsx
  client/src/components/auth/success-modal.tsx
  client/src/components/common/footer.tsx
  client/src/components/common/header.tsx
  client/src/components/common/logo.tsx
  client/src/components/common/modal.tsx
  client/src/components/common/navbar.tsx
  client/src/components/form/button.tsx
  client/src/components/form/input.tsx
  client/src/lib/woowahan-components/index.ts
  client/src/pages/not-found-page.tsx
  client/src/pages/signup-page.tsx
Labels: front-end, 중요도-trival

#79 Feature/#76 라우트 경로 재사용화
  client/src/App.tsx
  client/src/components/auth/form.tsx
  client/src/components/common/header.tsx
  client/src/components/common/navbar.tsx
  client/src/components/item/item-list.tsx
  client/src/components/smart-menu/large-menu.tsx
  client/src/components/smart-menu/medium-menu.tsx
  client/src/constants/urls.ts
  client/src/containers/category-container.tsx
  client/src/containers/login-container.tsx
  client/src/containers/search-container.tsx
  client/src/containers/signup-container.tsx
  client/src/lib/router/components/browser-router.tsx
  client/src/lib/router/context/router-context.ts
  client/src/lib/router/hooks/use-query.ts
  client/src/lib/router/index.ts
  client/src/pages/auth-page.tsx
  client/src/pages/item-list-page.tsx
  client/src/utils/index.ts
Labels: front-end, 중요도-trival

#83 Feature/#73 백엔드 검색 및 카테고리 아이템리스트 합치기
  server/src/controllers/items.ts
  server/src/repositories/items.ts
  server/src/routes/items/index.ts
  server/src/services/items.ts
Labels: feature, back-end, 중요도-major

#84 Feature/#78 프론트검색 및 아이템 ui
  client/src/App.tsx
  client/src/components/item/item-list-wrapper.tsx
  client/src/components/item/main-item-wrapper.tsx
  client/src/components/smart-menu/index.tsx
  client/src/components/smart-menu/large-menu.tsx
  client/src/components/smart-menu/medium-menu.tsx
  client/src/containers/category-container.tsx
  client/src/containers/item-list-container.tsx
  client/src/containers/main-item-container.tsx
  client/src/lib/router/components/route.tsx
  client/src/lib/router/hooks/use-query.ts
  client/src/pages/category-page.tsx
  client/src/pages/index.ts
  client/src/pages/item-list-page.tsx
  client/src/pages/main-page.tsx
  client/src/store/items.ts
  client/src/store/loading.ts
  client/src/utils/api/items.ts
  server/src/services/items.ts
Labels: feature, front-end, 중요도-major, 중요도-critical

#85 Feature/#81 메인 페이지 UI 작업
  client/src/assets/images/beer.png
  client/src/components/common/banner.tsx
  client/src/components/index.ts
  client/src/components/item/display-item-list.tsx
  client/src/components/item/index.tsx
  client/src/components/item/item-list.tsx
  client/src/components/item/main-item-wrapper.tsx
  client/src/components/search-bar/index.tsx
  client/src/pages/main-page.tsx
Labels: front-end, 중요도-major

#90 Feature/#89 설정 변경 및 아이템 옵션 추가 + 아이템전체개수 + 크론탭
  client/src/components/item/item-list-wrapper.tsx
  client/src/components/item/item-list.tsx
  client/src/containers/item-list-container.tsx
  client/src/store/auth.ts
  client/src/store/items.ts
  client/src/types/error.ts
  client/src/types/item.ts
  client/src/utils/api/items.ts
  server/src/controllers/items.ts
  server/src/models/item.ts
  server/src/models/user.ts
  server/src/repositories/items.ts
  server/src/services/items.ts
Labels: back-end, 중요도-major

#95 feature/#82 우아한 컴포넌트 리팩토링
  client/src/lib/woowahan-components/components/woowahan-component.tsx
  client/src/lib/woowahan-components/configs/react-props.ts
  client/src/lib/woowahan-components/index.ts
Labels: front-end, 중요도-minor

#98 Feature/#92 아이템 리스트 페이지 완성
  client/src/components/common/loader.tsx
  client/src/components/common/modal.tsx
  client/src/components/index.ts
  client/src/components/item/display-item-list.tsx
  client/src/components/item/filter.tsx
  client/src/components/item/index.tsx
  client/src/components/item/item-list-wrapper.tsx
  client/src/components/item/item-list.tsx
  client/src/components/item/item-loader.tsx
  client/src/components/item/main-item-wrapper.tsx
  client/src/components/item/pagination.tsx
  client/src/constants/index.ts
  client/src/containers/item-list-container.tsx
  client/src/containers/main-item-container.tsx
  client/src/pages/item-list-page.tsx
  client/src/store/index.ts
  client/src/store/item.ts
  client/src/store/items.ts
  client/src/store/loading.ts
  client/src/styles/theme.tsx
  client/src/types/item.ts
  client/src/types/search.ts
  client/src/utils/api/item.ts
  client/src/utils/api/items.ts
  server/src/controllers/items.ts
  server/src/repositories/items.ts
  server/src/services/items.ts
Labels: front-end, back-end, 중요도-major

#100 Feature/#91 제품 상세 페이지 레이아웃 및 UI
  client/.eslintrc.json
  client/src/components/common/layout/index.tsx
  client/src/components/common/text-button.tsx
  client/src/components/item-detail/detail-info.tsx
  client/src/components/item-detail/detail-wrapper.tsx
  client/src/components/item-detail/index.tsx
  client/src/components/item-detail/info-section.tsx
  client/src/components/item-detail/item-counter.tsx
  client/src/containers/item-detail-container.tsx
  client/src/lib/router/context/route-context.ts
  client/src/pages/item-detail-page.tsx
  client/src/styles/theme.tsx
Labels: feature, front-end, 중요도-blocker

#99 Feature/#96 메인 맞춤 상품 추천
  client/src/components/item/index.tsx
  client/src/styles/theme.tsx
  client/src/utils/api/item.ts
  server/src/controllers/items.ts
  server/src/models/index.ts
  server/src/models/score.ts
  server/src/repositories/items.ts
  server/src/routes/items/index.ts
  server/src/services/items.ts
Labels: feature, front-end, back-end, 중요도-major

#103 Feature/#97 주문목록조회 페이지 ui
  client/src/App.tsx
  client/src/components/auth/form.tsx
  client/src/components/common/menu-header.tsx
  client/src/components/my/inquiry-period.tsx
  client/src/components/my/my-bar.tsx
  client/src/components/my/my-order-list.tsx
  client/src/components/my/my-order.tsx
  client/src/components/my/my-status-bar.tsx
  client/src/containers/my-order-list-container.tsx
  client/src/lib/router/path-validation.ts
  client/src/lib/woowahan-components/configs/react-props.ts
  client/src/pages/index.ts
  client/src/pages/my-order-list-page.tsx
  client/src/utils/date.ts
Labels: front-end, 중요도-major

#109 Feature/#104 주문내역 불러오기 백엔드
  server/src/controllers/orders.ts
  server/src/loaders/sequelize.ts
  server/src/middlewares/validateToken.ts
  server/src/models/item.ts
  server/src/models/order.ts
  server/src/models/review.ts
  server/src/models/user.ts
  server/src/repositories/auth.ts
  server/src/repositories/items.ts
  server/src/repositories/orders.ts
  server/src/repositories/user.ts
  server/src/routes/index.ts
  server/src/routes/orders/index.ts
  server/src/services/auth.ts
  server/src/services/items.ts
  server/src/services/orders.ts
  server/src/services/user.ts
  server/src/utils/error/error-handler.ts
  server/src/validation/orders.ts
Labels: feature, back-end, 중요도-major

#112 Feature/#108 아이템 리스트 페이지 추천순 정렬
  client/src/utils/api/item.ts
  server/src/controllers/items.ts
  server/src/repositories/items.ts
  server/src/routes/items/index.ts
  server/src/services/items.ts
Labels: front-end, back-end, 중요도-major

#113 Feature/#102 이미지 확대 뷰어 개발
  client/src/components/image-viewer/index.tsx
  client/src/components/item-detail/info-section.tsx
Labels: front-end, 중요도-major

#119 Feature/#106 주문하기 페이지 UI
  client/src/App.tsx
  client/src/components/common/grid-form.tsx
  client/src/components/common/layout/index.tsx
  client/src/components/common/price-calculator.tsx
  client/src/components/common/table.tsx
  client/src/components/common/text-button.tsx
  client/src/components/order/index.tsx
  client/src/components/order/table-section.tsx
  client/src/pages/index.ts
  client/src/pages/order-page.tsx
  client/src/utils/validation/order-validation.ts
Labels: feature, front-end, 중요도-blocker

#117 Feature/#111 프론트 리덕스 스토어, 사가 분리
  client/src/saga/auth.ts
  client/src/saga/category.ts
  client/src/saga/item.ts
  client/src/saga/order.ts
  client/src/store/auth.ts
  client/src/store/category.ts
  client/src/store/item.ts
  client/src/store/order.ts
  client/src/types/auth.ts
  client/src/utils/api/auth.ts
Labels: front-end, 중요도-minor

#125 Feature/#121 주문하기 API
  client/src/utils/validation/order-validation.ts
  server/src/config/constants.ts
  server/src/controllers/orders.ts
  server/src/models/order.ts
  server/src/repositories/orders.ts
  server/src/routes/orders/index.ts
  server/src/services/orders.ts
  server/src/validation/orders.ts
Labels: feature, back-end, 중요도-blocker

#123 Feature/#122 배송지 관리 백엔드
  server/src/config/constants.ts
  server/src/controllers/address.ts
  server/src/models/address.ts
  server/src/repositories/address.ts
  server/src/routes/address/index.ts
  server/src/routes/index.ts
  server/src/services/address.ts
  server/src/utils/error/error-handler.ts
  server/src/validation/address.ts
  server/src/validation/orders.ts
Labels: back-end, 중요도-major

#128 Feature/#118 사가 테스트 코드
  client/jest.config.js
  client/package.json
  client/src/components/common/__test__/layout.test.tsx
  client/src/components/common/__test__/logo.test.tsx
  client/src/components/common/__test__/navbar.test.tsx
  client/src/components/search-bar/__test__/search-bar.test.tsx
  client/src/components/smart-menu/__test__/smart-menu.test.tsx
  client/src/constants/index.ts
  client/src/saga/__test__/auth.test.ts
  client/src/saga/__test__/category.test.ts
  client/src/saga/__test__/item.test.ts
  client/src/saga/__test__/order.test.ts
  client/src/saga/auth.ts
  client/src/saga/category.ts
  client/src/saga/item.ts
  client/src/saga/order.ts
  client/src/store/auth.ts
  client/src/store/item.ts
  client/src/store/order.ts
  client/yarn.lock
Labels: feature, front-end, 중요도-major

#130 Fix/#127 토큰 설정 관련 버그 수정
  client/src/App.tsx
  client/src/components/order/index.tsx
  client/src/containers/my-order-list-container.tsx
  client/src/containers/navbar-container.tsx
  client/src/containers/signin-container.tsx
  client/src/containers/signup-container.tsx
  client/src/pages/auth-page.tsx
  client/src/saga/__test__/auth.test.ts
  client/src/saga/__test__/order.test.ts
  client/src/saga/auth.ts
  client/src/saga/order.ts
  client/src/store/auth.ts
  client/src/store/category.ts
  client/src/store/item.ts
  client/src/store/loading.ts
  client/src/store/order.ts
  client/src/types/auth.ts
  client/src/utils/api/auth.ts
  client/src/utils/api/order.ts
Labels: bug, front-end, 중요도-major

#135 Feature/#129 배송지관리 프론트엔드
  client/src/App.tsx
  client/src/components/my/my-address/my-address-form.tsx
  client/src/components/my/my-address/my-address-table.tsx
  client/src/components/my/my-order-table.tsx
  client/src/containers/my-address-container.tsx
  client/src/containers/my-order-list-container.tsx
  client/src/pages/index.ts
  client/src/pages/my-address-page.tsx
  client/src/saga/__test__/address.test.ts
  client/src/saga/__test__/category.test.ts
  client/src/saga/address.ts
  client/src/saga/category.ts
  client/src/store/address.ts
  client/src/store/index.ts
  client/src/store/loading.ts
  client/src/types/address.ts
  client/src/utils/api/address.ts
  server/src/controllers/address.ts
  server/src/repositories/address.ts
  server/src/services/address.ts
  server/src/utils/error/error-handler.ts
Labels: front-end, 중요도-major

#193 Feature/#190 주말 프론트 작업
  client/package.json
  client/src/components/common/address-modal.tsx
  client/src/components/common/grid-form.tsx
  client/src/components/common/navbar.tsx
  client/src/components/common/period-selector.tsx
  client/src/components/common/price-calculator.tsx
  client/src/components/item-detail/detail.tsx
  client/src/components/item-detail/item-counter.tsx
  client/src/components/my/my-address/my-address-form.tsx
  client/src/components/my/my-order-list.tsx
  client/src/components/my/my-order.tsx
  client/src/components/order/index.tsx
  client/src/components/order/radio-button.tsx
  client/src/containers/my-address-container.tsx
  client/src/containers/my-order-list-container.tsx
  client/src/containers/order-container.tsx
  client/yarn.lock
Labels: front-end, 중요도-major

#194 Feature/#173 스마트 메뉴 작동방식 수정
  client/src/components/smart-menu/index.tsx
  client/src/components/smart-menu/large-menu.tsx
  client/src/components/smart-menu/medium-menu.tsx
  client/src/constants/index.ts
  client/src/utils/checkWidth.ts
Labels: bug, front-end, 중요도-minor

#197 Feature/#132 백엔드 리팩토링
  server/src/controllers/address.ts
  server/src/controllers/auth.ts
  server/src/controllers/items.ts
  server/src/controllers/like.ts
  server/src/controllers/orders.ts
  server/src/controllers/search.ts
  server/src/controllers/user.ts
  server/src/models/item.ts
  server/src/repositories/category.ts
  server/src/repositories/items.ts
  server/src/repositories/like.ts
  server/src/repositories/orders.ts
  server/src/repositories/reviews.ts
  server/src/repositories/search.ts
  server/src/routes/auth/index.ts
  server/src/services/auth.ts
  server/src/services/category.ts
  server/src/services/items.ts
  server/src/services/like.ts
  server/src/services/orders.ts
  server/src/services/reviews.ts
  server/src/services/search.ts
  server/src/types/address.ts
  server/src/types/auth.ts
  server/src/utils/error/error-handler.ts
  server/src/validation/address.ts
  server/src/validation/auth.ts
  server/src/validation/orders.ts
Labels: back-end, refactor, 중요도-minor

#198 Feature/#154 리액트 최적화
  client/src/components/common/layout/footer.tsx
  client/src/components/common/layout/header.tsx
  client/src/components/common/navbar.tsx
  client/src/components/item-detail/detail-wrapper.tsx
  client/src/components/smart-menu/index.tsx
  client/src/containers/item-detail-container.tsx
  client/src/containers/main-item-container.tsx
  client/src/containers/my-address-container.tsx
  client/src/containers/my-order-list-container.tsx
  client/src/containers/navbar-container.tsx
  client/src/containers/order-container.tsx
  client/src/containers/search-item-container.tsx
  client/src/containers/signin-container.tsx
  client/src/containers/signup-container.tsx
  client/src/containers/smart-menu-container.tsx
Labels: 중요도-minor

#199 Feature/#191 백엔드 개선사항 수정
  client/src/components/common/navbar.tsx
  client/src/components/item-detail/item-info.tsx
  client/src/components/my/my-address/my-address-form.tsx
  client/src/components/my/my-address/my-address-table.tsx
  client/src/components/order/index.tsx
  client/src/components/order/table-section.tsx
  client/src/containers/item-detail-container.tsx
  client/src/containers/my-address-container.tsx
  client/src/containers/order-container.tsx
  client/src/store/item.ts
  client/src/types/address.ts
  client/src/types/item.ts
  client/src/utils/api/address.ts
  client/src/utils/validation/order-validation.ts
  server/src/controllers/address.ts
  server/src/models/address.ts
  server/src/repositories/address.ts
  server/src/repositories/items.ts
  server/src/services/address.ts
  server/src/services/items.ts
  server/src/types/address.ts
  server/src/validation/address.ts
Labels: 중요도-major

#200 Fix/#185 페이지네이션 및 정렬을 url query 방식으로 변경
  client/src/components/common/pagination.tsx
  client/src/components/item-detail/detail.tsx
  client/src/components/item/search-item/filter.tsx
  client/src/components/item/search-item/search-item-wrapper.tsx
  client/src/components/my/my-order/my-order-table.tsx
  client/src/containers/item-detail-container.tsx
  client/src/containers/my-order-list-container.tsx
  client/src/containers/search-item-container.tsx
  client/src/lib/woowahan-components/components/woowahan-component.tsx
  client/src/lib/woowahan-components/configs/react-props.ts
  client/src/types/order.ts
  server/src/repositories/orders.ts
  server/src/services/items.ts
Labels: bug, 중요도-major

#202 Feature/#196 react title 적용
  client/package.json
  client/src/constants/index.ts
  client/src/containers/item-detail-container.tsx
  client/src/index.tsx
  client/src/pages/cart-page.tsx
  client/src/pages/item-list-page.tsx
  client/src/pages/main-page.tsx
  client/src/pages/my-address-page.tsx
  client/src/pages/my-order-list-page.tsx
  client/src/pages/not-found-page.tsx
  client/src/pages/order-page.tsx
  client/src/pages/signin-page.tsx
  client/src/pages/signup-page.tsx
  client/yarn.lock
Labels: front-end, 중요도-minor

#201 Feature/#192 사파리 적용되지 않는 style 수정
  client/src/components/cart/index.tsx
  client/src/components/common/navbar.tsx
  client/src/components/common/price-calculator.tsx
  client/src/components/search-bar/index.tsx
Labels: 중요도-trival, only-UI

#204 Feature/#203 스마트 메뉴 오류 수정
  client/src/components/smart-menu/index.tsx
Labels: bug, front-end

#207 Feature/#206 장바구니를 redux에서 관리
  client/src/components/cart/index.tsx
  client/src/components/common/navbar.tsx
  client/src/containers/item-detail-container.tsx
  client/src/containers/navbar-container.tsx
  client/src/containers/order-container.tsx
  client/src/index.tsx
  client/src/store/cart.ts
  client/src/store/index.ts
  client/src/utils/cart-generator.ts
Labels: bug, front-end
